apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
     apps.open-cluster-management.io/is-local-deployable: "true"
  name: lab1-tradr-config
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: lab1-tradr-config
    data:
      stockQuote.url: "stockquote.com"
      tradeHistory.url: "tradehistory.com"
      portfolio.url: "portfolio.com"
