apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
    apps.open-cluster-management.io/is-local-deployable: "true"
  name: lab1-tradr-service
  labels:
    apps.open-cluster-management.io/channel: lab1-tradr-channel
    apps.open-cluster-management.io/channel-type: Namespace
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: lab1-tradr-service
    spec:
      selector:
        app: lab1-tradr
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
